#include "stdafx.h"
#include "extras.h"

extern ::HMODULE hModuleInstance;

char* extras::partNames[]= {"Default", "Bonnet", "Boot", "Front Bumper", "Rear Bumper", "Left Front Door",
					"Right Front Door", "Left Rear Door", "Right Rear Door", "Left Front Wing",
					"Right Front Wing", "Left Rear Wing", "Right Rear Wing", "ID 13", "ID 14", "ID 15",
					"ID 16", "Windscreen"};
char* extras::surfaceNames[] = { "DEFAULT",
 "TARMAC", "TARMAC_FUCKED", "TARMAC_REALLYFUCKED", "PAVEMENT", "PAVEMENT_FUCKED",
 "GRAVEL", "FUCKED_CONCRETE", "PAINTED_GROUND", "GRASS_SHORT_LUSH", "GRASS_MEDIUM_LUSH",
 "GRASS_LONG_LUSH", "GRASS_SHORT_DRY", "GRASS_MEDIUM_DRY", "GRASS_LONG_DRY", "GOLFGRASS_ROUGH",
 "GOLFGRASS_SMOOTH", "STEEP_SLIDYGRASS", "STEEP_CLIFF", "FLOWERBED", "MEADOW",
 "WASTEGROUND", "WOODLANDGROUND", "VEGETATION", "MUD_WET", "MUD_DRY",
 "DIRT", "DIRTTRACK", "SAND_DEEP", "SAND_MEDIUM", "SAND_COMPACT",
 "SAND_ARID", "SAND_MORE", "SAND_BEACH", "CONCRETE_BEACH", "ROCK_DRY",
 "ROCK_WET", "ROCK_CLIFF", "WATER_RIVERBED", "WATER_SHALLOW", "CORNFIELD",
 "HEDGE", "WOOD_CRATES", "WOOD_SOLID", "WOOD_THIN", "GLASS",
 "GLASS_WINDOWS_LARGE", "GLASS_WINDOWS_SMALL", "EMPTY1", "EMPTY2", "GARAGE_DOOR",
 "THICK_METAL_PLATE", "SCAFFOLD_POLE", "LAMP_POST", "METAL_GATE", "METAL_CHAIN_FENCE",
 "GIRDER", "FIRE_HYDRANT", "CONTAINER", "NEWS_VENDOR", "WHEELBASE",
 "CARDBOARDBOX", "PED", "CAR", "CAR_PANEL", "CAR_MOVINGCOMPONENT",
 "TRANSPARENT_CLOTH", "RUBBER", "PLASTIC", "TRANSPARENT_STONE", "WOOD_BENCH",
 "CARPET", "FLOORBOARD", "STAIRSWOOD", "P_SAND", "P_SAND_DENSE",
 "P_SAND_ARID", "P_SAND_COMPACT", "P_SAND_ROCKY", "P_SANDBEACH", "P_GRASS_SHORT",
 "P_GRASS_MEADOW", "P_GRASS_DRY", "P_WOODLAND", "P_WOODDENSE", "P_ROADSIDE",
 "P_ROADSIDEDES", "P_FLOWERBED", "P_WASTEGROUND", "P_CONCRETE", "P_OFFICEDESK",
 "P_711SHELF1", "P_711SHELF2", "P_711SHELF3", "P_RESTUARANTTABLE", "P_BARTABLE",
 "P_UNDERWATERLUSH", "P_UNDERWATERBARREN", "P_UNDERWATERCORAL", "P_UNDERWATERDEEP", "P_RIVERBED",
 "P_RUBBLE", "P_BEDROOMFLOOR", "P_KIRCHENFLOOR", "P_LIVINGRMFLOOR", "P_CORRIDORFLOOR",
 "P_711FLOOR", "P_FASTFOODFLOOR", "P_SKANKYFLOOR", "P_MOUNTAIN", "P_MARSH",
 "P_BUSHY", "P_BUSHYMIX", "P_BUSHYDRY", "P_BUSHYMID", "P_GRASSWEEFLOWERS",
 "P_GRASSDRYTALL", "P_GRASSLUSHTALL", "P_GRASSGRNMIX", "P_GRASSBRNMIX", "P_GRASSLOW",
 "P_GRASSROCKY", "P_GRASSSMALLTREES", "P_DIRTROCKY", "P_DIRTWEEDS", "P_GRASSWEEDS",
 "P_RIVEREDGE", "P_POOLSIDE", "P_FORESTSTUMPS", "P_FORESTSTICKS", "P_FORRESTLEAVES",
 "P_DESERTROCKS", "P_FORRESTDRY", "P_SPARSEFLOWERS", "P_BUILDINGSITE", "P_DOCKLANDS",
 "P_INDUSTRIAL", "P_INDUSTJETTY", "P_CONCRETELITTER", "P_ALLEYRUBISH", "P_JUNKYARDPILES",
 "P_JUNKYARDGRND", "P_DUMP", "P_CACTUSDENSE", "P_AIRPORTGRND", "P_CORNFIELD",
 "P_GRASSLIGHT", "P_GRASSLIGHTER", "P_GRASSLIGHTER2", "P_GRASSMID1", "P_GRASSMID2",
 "P_GRASSDARK", "P_GRASSDARK2", "P_GRASSDIRTMIX", "P_RIVERBEDSTONE", "P_RIVERBEDSHALLOW",
 "P_RIVERBEDWEEDS", "P_SEAWEED", "DOOR", "PLASTICBARRIER", "PARKGRASS",
 "STAIRSSTONE", "STAIRSMETAL", "STAIRSCARPET", "FLOORMETAL", "FLOORCONCRETE",
 "BIN_BAG", "THIN_METAL_SHEET", "METAL_BARREL", "PLASTIC_CONE", "PLASTIC_DUMPSTER",
 "METAL_DUMPSTER", "WOOD_PICKET_FENCE", "WOOD_SLATTED_FENCE", "WOOD_RANCH_FENCE", "UNBREAKABLE_GLASS",
 "HAY_BALE", "GORE", "RAILTRACK" };

std::string _stdcall extras::GetRscString(UINT resourceID)
{
	char RscBuffer[50];
	LoadString(hModuleInstance, resourceID, RscBuffer, 50);
	return RscBuffer;
}

std::string extras::GetShortFilename(const char* LongFilename, std::string* path)
{
	int index;
	for (index= strlen(LongFilename); index >= 0; --index)
	{
		if (LongFilename[index] == '\\' )
			break;
	}
	if (path)
		*path= (LongFilename+index);
	return std::string(LongFilename+index+1);
}

std::string extras::GetShortFilename(const std::string& LongFilename, std::string* path)
{
	int index;
	for (index= LongFilename.length()-1; index >= 0; --index)
	{
		if (LongFilename[index] == '\\' )
			break;
	}
	if (path)
		*path= LongFilename.substr(0, index+1);
	return LongFilename.substr(index+1);
}